version: '3.8'

services:
  web:
    build:
      context: ./
      args:
        PYTHON_VERSION: 3.8
    command: python3 manage.py runserver 0.0.0.0:80
    volumes:
      - ./:/usr/src/app/
    ports:
      - 80:80
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust